#!/usr/bin/env bash
set -euo pipefail

BASE_DIR="$(cd "$(dirname "$(readlink -f "$0")")" && pwd)/passgen-lib"

source "/usr/local/bin/passgen-lib/help.sh"
source "/usr/local/bin/passgen-lib/utils.sh"
source "/usr/local/bin/passgen-lib/banner.sh"
source "/usr/local/bin/passgen-lib/generator.sh"

handle_cli "$@"

clear
show_banner
run_generator